# This is a basic workflow to help you get started with Actions

name: juantxitos-chords-deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          apt-get update && apt-get upgrade && apt-get install -y build-essential perl libwx-perl mupdf cpanminus
          apt-get install --no-install-recommends -y libxml-perl libfile-homedir-perl libfont-ttf-perl libpdf-api2-perl libobject-pad-perl libimage-info-perl abcm2ps imagemagick librsvg2-bin libimage-magick-perl && apt-get clean && rm -rf /var/lib/apt/lists/*
          cpanm File::LoadLines String::Interpolate::Named HarfBuzz::Shaper Text::Layout
          cpanm chordpro
          chordpro --about
